# Generated by Django 2.1.3 on 2019-01-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='piars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('text1', models.TextField()),
                ('id2', models.IntegerField()),
                ('text2', models.TextField()),
                ('samplingMethod', models.CharField(max_length=128)),
                ('task', models.CharField(max_length=128)),
                ('is_same', models.IntegerField(default=-1)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
