# Generated by Django 2.1.3 on 2019-01-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0002_piars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedid', models.IntegerField()),
                ('text1', models.TextField()),
                ('candidateidset', models.TextField(blank=True)),
                ('selectedidset', models.TextField(blank=True)),
                ('samplingMethod', models.CharField(max_length=128)),
                ('task', models.CharField(max_length=128)),
                ('is_checked', models.IntegerField(default=-1)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
