# Generated by Django 2.1.3 on 2019-01-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0003_multiitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiitems',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
