# Generated by Django 2.1.3 on 2019-01-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0007_cora_labeled_cleantext'),
        ('sigirexperiments', '0004_multiitems_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='dextraitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(max_length=128)),
                ('msg', models.TextField(blank=True)),
                ('samplingMethod', models.CharField(max_length=128)),
                ('task', models.CharField(max_length=128)),
                ('optype', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='sigirAttrExploration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substring', models.CharField(max_length=128)),
                ('orderscore', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sigirCoraAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(max_length=128)),
                ('attrscope', models.CharField(max_length=128)),
                ('is_alive', models.BooleanField()),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sigirCoraAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('userid', models.IntegerField(default=0)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigirexperiments.sigirCoraAttr')),
            ],
        ),
        migrations.CreateModel(
            name='sigirCoraToAttrEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sigirCoraValueSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=300)),
                ('userid', models.IntegerField(default=0)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigirexperiments.sigirCoraAttrValue')),
            ],
        ),
        migrations.AddField(
            model_name='sigircoratoattrentity',
            name='attrsynonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigirexperiments.sigirCoraValueSynonym'),
        ),
        migrations.AddField(
            model_name='sigircoratoattrentity',
            name='cora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERtasks.Cora'),
        ),
    ]
