# Generated by Django 2.1.3 on 2019-01-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0005_auto_20190110_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigirattrexploration',
            name='is_labelled',
            field=models.BooleanField(default=False),
        ),
    ]
