# Generated by Django 2.1.3 on 2019-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0006_sigirattrexploration_is_labelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='patternSeedTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedsubstring', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='sigirattrexploration',
            name='user',
            field=models.CharField(default='aming', max_length=128),
        ),
        migrations.AddField(
            model_name='sigircoratoattrentity',
            name='user',
            field=models.CharField(default='aming', max_length=128),
        ),
    ]
