# Generated by Django 2.1.3 on 2019-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigirexperiments', '0007_auto_20190111_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternseedtemp',
            name='user',
            field=models.CharField(default='', max_length=128),
        ),
    ]
