# Generated by Django 2.1.1 on 2018-09-10 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_worklog'),
        ('baselinealloy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cora1_id', models.IntegerField()),
                ('cora2_id', models.IntegerField()),
                ('is_same', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.WorkerInfo')),
            ],
        ),
        migrations.CreateModel(
            name='tail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cora1_id', models.IntegerField()),
                ('cora2_id', models.IntegerField()),
                ('is_same', models.IntegerField(default=-1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.WorkerInfo')),
            ],
        ),
    ]
