# Generated by Django 2.1.1 on 2018-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoraAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attrname', models.CharField(max_length=128)),
                ('attrscope', models.CharField(max_length=128)),
                ('is_alive', models.BooleanField()),
                ('userid', models.IntegerField()),
            ],
        ),
    ]
