# Generated by Django 2.1.1 on 2018-09-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0001_initial'),
        ('DEXTRA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoraAttrValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DEXTRA.CoraAttr')),
            ],
        ),
        migrations.CreateModel(
            name='CoraToAttrEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoraValueSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=300)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DEXTRA.CoraAttrValue')),
            ],
        ),
        migrations.AddField(
            model_name='coratoattrentity',
            name='attrsynonym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DEXTRA.CoraValueSynonym'),
        ),
        migrations.AddField(
            model_name='coratoattrentity',
            name='cora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERtasks.Cora'),
        ),
    ]
