# Generated by Django 2.1.1 on 2018-09-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('operate_message', models.TextField(blank=True)),
                ('task', models.CharField(max_length=128)),
                ('operate_flag', models.CharField(max_length=128)),
                ('operate_user', models.CharField(max_length=128)),
            ],
        ),
    ]
