# Generated by Django 2.1.1 on 2018-09-10 05:36

from django.db import migrations, models
import pyweb.dxaconstants


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='operate_system',
            field=models.CharField(default=pyweb.dxaconstants.TestSystems(1), max_length=128),
        ),
    ]
