# Generated by Django 2.1.1 on 2018-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_worklog_operate_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='operate_system',
            field=models.CharField(max_length=128),
        ),
    ]
