# Generated by Django 2.1.1 on 2018-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cora',
            name='attributedtext',
            field=models.TextField(default=models.TextField()),
        ),
    ]
