# Generated by Django 2.1.1 on 2018-09-09 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0002_cora_attributedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='crowdCora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testsystem', models.CharField(max_length=128)),
                ('clusterid', models.IntegerField(default=0)),
                ('cora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERtasks.Cora')),
            ],
        ),
    ]
