# Generated by Django 2.1.3 on 2019-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0006_cora_labeled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cora_labeled',
            name='cleantext',
            field=models.TextField(default=models.TextField()),
        ),
    ]
