# Generated by Django 2.1.3 on 2019-01-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERtasks', '0007_cora_labeled_cleantext'),
    ]

    operations = [
        migrations.AddField(
            model_name='cora_labeled',
            name='orderscore',
            field=models.FloatField(default=0),
        ),
    ]
