# Generated by Django 2.1.1 on 2018-09-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uncertainpiars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('text1', models.TextField()),
                ('id2', models.IntegerField()),
                ('text2', models.TextField()),
                ('task', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
