# Generated by Django 2.1.1 on 2018-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselinededupe', '0002_uncertainpiars_is_same'),
    ]

    operations = [
        migrations.CreateModel(
            name='blocking_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_key', models.CharField(max_length=200)),
                ('data_id', models.IntegerField()),
            ],
        ),
    ]
