# Generated by Django 2.1.1 on 2018-09-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselinededupe', '0003_blocking_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusterTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_record_id', models.IntegerField()),
                ('task', models.CharField(max_length=128)),
                ('clusterid', models.IntegerField(default=0)),
                ('confidence', models.FloatField()),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
