# Generated by Django 2.1.1 on 2018-09-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselinededupe', '0004_clustertemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='clusterCanonicalRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterid', models.IntegerField()),
                ('canonrep', models.TextField()),
                ('task', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
            ],
        ),
    ]
